/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurante2;

import Datos.ObjetoCompartido;
import Datos.Reserva;
import Modelo.KeyValuePair;
import Negocio.ServicioConsulta;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.JOptionPane;

/**
 *
 * @author cjavi
 */
public class Restaurante extends javax.swing.JFrame {

    public ObjetoCompartido obj = new ObjetoCompartido();
    public Object[] obja;
    public DefaultTableModel model = new DefaultTableModel();
    public ServicioConsulta servicio = new ServicioConsulta();

    /**
     * Creates new form Restaurante
     */
    public Restaurante() {
        initComponents();
        jModificarReserva.setEnabled(false);
        jCancelarReserva.setEnabled(false);
        jGuardarReserva.setEnabled(false);

        List<KeyValuePair> lista = new ArrayList<>();
        lista.add(new KeyValuePair(1, "Confirmada"));
        lista.add(new KeyValuePair(2, "Cancelada"));

        for (KeyValuePair item : lista) {
            jComboBox1.insertItemAt(item.getValor(), item.getId());
        }

        obj.setSharedVariable(servicio.ObtenerRegistrosRestaurante());
        List<Reserva> lstReserva = new ArrayList<>();
        lstReserva = obj.getSharedVariable();
        for (Reserva reserva : lstReserva) {
            String valor = reserva.getNombreCliente();

        }

        Llenartabla(lstReserva);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jtxtNumeroDocumentoCliente1 = new javax.swing.JTextField();
        jtxtBuscador = new javax.swing.JTextField();
        jCancelarReserva = new javax.swing.JButton();
        jbuttonLimpiar = new javax.swing.JButton();
        jtxtNumeroContactoCliente = new javax.swing.JTextField();
        jcodigoreserva = new javax.swing.JTextField();
        jtxtNombreCliente = new javax.swing.JTextField();
        jtxtCorreoCliente = new javax.swing.JTextField();
        jtxtCantidadPersonas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCrearReserva = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jGuardarReserva = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jModificarReserva = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3310748.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1033, 768));
        setResizable(false);

        jtxtNumeroDocumentoCliente1.setToolTipText("");

        jCancelarReserva.setBackground(new java.awt.Color(0, 0, 0));
        jCancelarReserva.setForeground(new java.awt.Color(255, 255, 255));
        jCancelarReserva.setText("Cancelar Reserva seleccionada");
        jCancelarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelarReservaActionPerformed(evt);
            }
        });

        jbuttonLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        jbuttonLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jbuttonLimpiar.setText("Limpiar");
        jbuttonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonLimpiarActionPerformed(evt);
            }
        });

        jtxtNumeroContactoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNumeroContactoClienteActionPerformed(evt);
            }
        });

        jcodigoreserva.setEditable(false);
        jcodigoreserva.setToolTipText("");

        jtxtNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreClienteActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCrearReserva.setBackground(new java.awt.Color(0, 0, 0));
        jCrearReserva.setForeground(new java.awt.Color(255, 255, 255));
        jCrearReserva.setText("Crear reserva");
        jCrearReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearReservaActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Buscar Reserva");

        jLabel1.setBackground(new java.awt.Color(51, 0, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Reserva");

        jGuardarReserva.setBackground(new java.awt.Color(0, 0, 0));
        jGuardarReserva.setForeground(new java.awt.Color(255, 255, 255));
        jGuardarReserva.setText("Guardar Reserva");
        jGuardarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarReservaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jModificarReserva.setBackground(new java.awt.Color(0, 0, 0));
        jModificarReserva.setForeground(new java.awt.Color(255, 255, 255));
        jModificarReserva.setText("Modificar Reserva Seleccionada");
        jModificarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModificarReservaActionPerformed(evt);
            }
        });

        jLabel4.setText("Id Reserva");

        jLabel5.setText("Número Identificación");

        jLabel6.setText("Nombre Cliente");

        jLabel7.setText("Teléfono Cliente");

        jLabel8.setText("Correo Cliente");

        jLabel9.setText("Fecha Reserva");

        jLabel10.setText("Estado Reserva");

        jLabel11.setText("Cantidad  ");

        jToolBar1.setRollover(true);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3170733.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCrearReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jGuardarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(jCancelarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jModificarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtNumeroContactoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtNumeroDocumentoCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcodigoreserva, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtCantidadPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbuttonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addComponent(jLabel3))
                                    .addComponent(jtxtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbuttonLimpiar)
                                    .addComponent(jButton1))
                                .addGap(33, 33, 33))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(3, 3, 3)
                                .addComponent(jcodigoreserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtNumeroDocumentoCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtNumeroContactoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtCantidadPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCrearReserva)
                            .addComponent(jGuardarReserva)
                            .addComponent(jCancelarReserva)
                            .addComponent(jModificarReserva)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCancelarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCancelarReservaActionPerformed

    private void jbuttonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonLimpiarActionPerformed
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTable1.setRowSorter(sorter);
        jTable1.repaint();
        jtxtBuscador.setText("");
    }//GEN-LAST:event_jbuttonLimpiarActionPerformed

    private void jtxtNumeroContactoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNumeroContactoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNumeroContactoClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTable1.setRowSorter(sorter);

        // Crear un RowFilter para filtrar por ID
        RowFilter<Object, Object> rowFilter = RowFilter.regexFilter(jtxtBuscador.getText(), 0); // 0 indica la columna del ID
        sorter.setRowFilter(rowFilter);
        jTable1.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCrearReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearReservaActionPerformed
        jModificarReserva.setEnabled(false);
        jCancelarReserva.setEnabled(false);
        jGuardarReserva.setEnabled(true);
        jCrearReserva.setEnabled(false);

        List<Reserva> lstReserva = new ArrayList<>();
        lstReserva = obj.getSharedVariable();
        Date fecha = jDateChooser1.getDate();

        jcodigoreserva.setText("");
        jtxtNombreCliente.setText("");
        jtxtNumeroContactoCliente.setText("");
        jtxtNumeroDocumentoCliente1.setText("");
        jtxtCorreoCliente.setText("");
        jComboBox1.setSelectedItem("");
        jComboBox1.setSelectedIndex(0);
        jtxtCantidadPersonas.setText("");
        LocalDate fechaActual = LocalDate.now();
        jDateChooser1.setDate(java.sql.Date.valueOf(fechaActual));

    }//GEN-LAST:event_jCrearReservaActionPerformed

    private void LimpiarFormulario() {
        jcodigoreserva.setText("");
        jtxtNombreCliente.setText("");
        jtxtNumeroContactoCliente.setText("");
        jtxtNumeroDocumentoCliente1.setText("");
        jtxtCorreoCliente.setText("");
        jComboBox1.setSelectedItem("");
        jComboBox1.setSelectedIndex(0);
        jtxtCantidadPersonas.setText("");
        LocalDate fechaActual = LocalDate.now();
        jDateChooser1.setDate(java.sql.Date.valueOf(fechaActual));
    }

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        JComboBox<String> comboBox = (JComboBox<String>) evt.getSource();
        String valorSeleccionado = (String) comboBox.getSelectedItem();
        int indexSeleccionado = comboBox.getSelectedIndex();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jGuardarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarReservaActionPerformed
        jModificarReserva.setEnabled(false);
        jCancelarReserva.setEnabled(false);
        jGuardarReserva.setEnabled(false);
        jCrearReserva.setEnabled(true);

        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");

        // Convertir la fecha a un String
        String fechaString = formato.format(jDateChooser1.getDate());
        LocalDate localDate = LocalDate.parse(fechaString);
        Reserva reserva = new Reserva();

        reserva.setNombreCliente(jtxtNombreCliente.getText());
        reserva.setNumeroContactoCliente(jtxtNumeroContactoCliente.getText());
        reserva.setNumeroDocumentoCliente(jtxtNumeroDocumentoCliente1.getText());

        reserva.setFechaReserva(java.sql.Date.valueOf(localDate));
        reserva.setCorreoCliente(jtxtCorreoCliente.getText());
        reserva.setEstadoReserva((String) jComboBox1.getSelectedItem());
        reserva.setCantidadPersonas(Integer.parseInt(jtxtCantidadPersonas.getText()));

        boolean respuesta = servicio.InsertarReserva(reserva);
        obj.setSharedVariable(servicio.ObtenerRegistrosRestaurante());
        List<Reserva> lstReserva = new ArrayList<>();
        lstReserva = obj.getSharedVariable();
        Llenartabla(lstReserva);
        jCrearReserva.setEnabled(true);
        LimpiarFormulario();
        JOptionPane.showMessageDialog(null, "Reserva Creada exitosamente");

    }//GEN-LAST:event_jGuardarReservaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // Obtener la fila en la que se hizo clic
        int rowIndex = jTable1.getSelectedRow();

        jModificarReserva.setEnabled(true);
        jCancelarReserva.setEnabled(true);
        jGuardarReserva.setEnabled(true);

        // Verificar si se seleccionó una fila válida
        if (rowIndex != -1) {
            // Obtener los valores de todas las celdas en la fila seleccionada
            Object[] valoresFila = new Object[jTable1.getColumnCount()]; // Array para almacenar los valores de la fila
            for (int column = 0; column < jTable1.getColumnCount(); column++) {
                valoresFila[column] = jTable1.getValueAt(rowIndex, column);
            }
            jcodigoreserva.setText(valoresFila[0].toString());
            jtxtNombreCliente.setText(valoresFila[1].toString());
            jtxtNumeroContactoCliente.setText(valoresFila[2].toString());
            jtxtNumeroDocumentoCliente1.setText(valoresFila[3].toString());
            jtxtCorreoCliente.setText(valoresFila[4].toString());
            String fecha = valoresFila[5].toString();
            LocalDate localDate = LocalDate.parse(fecha);
            Date date = java.sql.Date.valueOf(localDate);
            jDateChooser1.setDate(date);
            jComboBox1.setSelectedItem(valoresFila[6].toString());
            jtxtCantidadPersonas.setText(valoresFila[7].toString());
    }//GEN-LAST:event_jTable1MouseClicked
    }


    private void jModificarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModificarReservaActionPerformed
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");

        // Convertir la fecha a un String
        String fechaString = formato.format(jDateChooser1.getDate());
        LocalDate localDate = LocalDate.parse(fechaString);
        Reserva reserva = new Reserva();
        reserva.setCodigo(Integer.parseInt(jcodigoreserva.getText()));

        reserva.setNombreCliente(jtxtNombreCliente.getText());
        reserva.setNumeroContactoCliente(jtxtNumeroContactoCliente.getText());
        reserva.setNumeroDocumentoCliente(jtxtNumeroDocumentoCliente1.getText());

        reserva.setFechaReserva(java.sql.Date.valueOf(localDate));
        reserva.setCorreoCliente(jtxtCorreoCliente.getText());
        reserva.setEstadoReserva((String) jComboBox1.getSelectedItem());
        reserva.setCantidadPersonas(Integer.parseInt(jtxtCantidadPersonas.getText()));

        boolean respuesta = servicio.actualizarReserva(reserva);
        obj.setSharedVariable(servicio.ObtenerRegistrosRestaurante());
        List<Reserva> lstReserva = new ArrayList<>();
        lstReserva = obj.getSharedVariable();
        Llenartabla(lstReserva);
        LimpiarFormulario();
        JOptionPane.showMessageDialog(null, "Reserva Modificada exitosamente");

    }//GEN-LAST:event_jModificarReservaActionPerformed

    private void jtxtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    private void Llenartabla(List<Reserva> lstReserva) {
        limpiarTabla(model);

        model.addColumn("Codigo");
        model.addColumn("Nombre del cliente");
        model.addColumn("Número de contacto del cliente");
        model.addColumn("Identificación Cliente");
        model.addColumn("Correo");
        model.addColumn("Fecha de la reserva");
        model.addColumn("Estado de la reserva");
        model.addColumn("Cantidad de Personas");

        for (Reserva reserva : lstReserva) {
            obja = new Object[]{
                reserva.getCodigo(),
                reserva.getNombreCliente(),
                reserva.getNumeroContactoCliente(),
                reserva.getNumeroDocumentoCliente(),
                reserva.getCorreoCliente(),
                reserva.getFechaReserva(),
                reserva.getEstadoReserva(),
                reserva.getCantidadPersonas()
            };
            model.addRow(obja);
        }

        jTable1.setModel(model);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurante().setVisible(true);
                Restaurante.setDefaultLookAndFeelDecorated(true);
            }
        });
    }

    public static void limpiarTabla(DefaultTableModel modeloTabla) {
        // Eliminar todas las filas del modelo de la tabla
        while (modeloTabla.getRowCount() > 0) {
            modeloTabla.removeRow(0);
        }
        modeloTabla.setColumnCount(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jCancelarReserva;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JButton jCrearReserva;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JButton jGuardarReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jModificarReserva;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbuttonLimpiar;
    private javax.swing.JTextField jcodigoreserva;
    private javax.swing.JTextField jtxtBuscador;
    private javax.swing.JTextField jtxtCantidadPersonas;
    private javax.swing.JTextField jtxtCorreoCliente;
    private javax.swing.JTextField jtxtNombreCliente;
    private javax.swing.JTextField jtxtNumeroContactoCliente;
    private javax.swing.JTextField jtxtNumeroDocumentoCliente1;
    // End of variables declaration//GEN-END:variables
}
